//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MasterDetails_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public int Year_Of_Experience { get; set; }
        public int Cid { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
